In [1]:
# CovidInfectionAnalysis
# Group Name: Endless Knot
# Group Members: Toni, Elsa, India, Utsav
# Machine Learning model MOCKUP

In [2]:
# Import Libraries
import pandas as pd
import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error
from sklearn.datasets import make_blobs
import sklearn as skl
import tensorflow as tf

In [3]:
# Read Dataset/load dataset
covidanalysis_to_load = "./Race_and_Ethnicity.csv"

In [4]:
covidanalysis_data_df = pd.read_csv(covidanalysis_to_load)

In [5]:
covidanalysis_data_df

,Date,state,Cases_Total,Cases_White,Cases_Black,Cases_Latinx,Cases_Asian,Cases_AIAN,Cases_NHPI,Cases_Multiracial,...,Tests_Latinx,Tests_Asian,Tests_AIAN,Tests_NHPI,Tests_Multiracial,Tests_Other,Tests_Unknown,Tests_Ethnicity_Hispanic,Tests_Ethnicity_NonHispanic,Tests_Ethnicity_Unknown
0,20210307,AK,59332.0,18300.0,1499.0,NaN,2447.0,12238.0,1508.0,4453.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20210307,AL,499819.0,160347.0,82790.0,NaN,2273.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20210307,AR,324818.0,207596.0,50842.0,NaN,2913.0,1070.0,3358.0,1804.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20210307,AS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20210307,AZ,826454.0,308453.0,25775.0,244539.0,11921.0,40707.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5315,20200412,VT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5316,20200412,WA,10411.0,2903.0,289.0,1180.0,451.0,41.0,61.0,112.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5317,20200412,WI,3341.0,1680.0,857.0,NaN,81.0,28.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5318,20200412,WV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5319,20200412,WY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
covidanalysis_data_df.columns

Index(['Date', 'state', 'Cases_Total', 'Cases_White', 'Cases_Black',
       'Cases_Latinx', 'Cases_Asian', 'Cases_AIAN', 'Cases_NHPI',
       'Cases_Multiracial', 'Cases_Other', 'Cases_Unknown',
       'Cases_Ethnicity_Hispanic', 'Cases_Ethnicity_NonHispanic',
       'Cases_Ethnicity_Unknown', 'Deaths_Total', 'Deaths_White',
       'Deaths_Black', 'Deaths_Latinx', 'Deaths_Asian', 'Deaths_AIAN',
       'Deaths_NHPI', 'Deaths_Multiracial', 'Deaths_Other', 'Deaths_Unknown',
       'Deaths_Ethnicity_Hispanic', 'Deaths_Ethnicity_NonHispanic',
       'Deaths_Ethnicity_Unknown', 'Hosp_Total', 'Hosp_White', 'Hosp_Black',
       'Hosp_Latinx', 'Hosp_Asian', 'Hosp_AIAN', 'Hosp_NHPI',
       'Hosp_Multiracial', 'Hosp_Other', 'Hosp_Unknown',
       'Hosp_Ethnicity_Hispanic', 'Hosp_Ethnicity_NonHispanic',
       'Hosp_Ethnicity_Unknown', 'Tests_Total', 'Tests_White', 'Tests_Black',
       'Tests_Latinx', 'Tests_Asian', 'Tests_AIAN', 'Tests_NHPI',
       'Tests_Multiracial', 'Tests_Other', 'Tests_Unknown',
       'Tests_Ethnicity_Hispanic', 'Tests_Ethnicity_NonHispanic',
       'Tests_Ethnicity_Unknown'],
      dtype='object')

In [7]:
# Normalize the data. Find Null 
covidanalysis_data_df.isnull()

,Date,state,Cases_Total,Cases_White,Cases_Black,Cases_Latinx,Cases_Asian,Cases_AIAN,Cases_NHPI,Cases_Multiracial,...,Tests_Latinx,Tests_Asian,Tests_AIAN,Tests_NHPI,Tests_Multiracial,Tests_Other,Tests_Unknown,Tests_Ethnicity_Hispanic,Tests_Ethnicity_NonHispanic,Tests_Ethnicity_Unknown
0,False,False,False,False,False,True,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
1,False,False,False,False,False,True,False,True,True,True,...,True,True,True,True,True,True,True,True,True,True
2,False,False,False,False,False,True,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
3,False,False,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
4,False,False,False,False,False,False,False,False,True,True,...,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5315,False,False,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
5316,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
5317,False,False,False,False,False,True,False,False,True,True,...,True,True,True,True,True,True,True,True,True,True
5318,False,False,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
5319,False,False,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True

In [8]:
covidanalysis_df = covidanalysis_data_df.fillna(0)

In [9]:
covidanalysis_df

,Date,state,Cases_Total,Cases_White,Cases_Black,Cases_Latinx,Cases_Asian,Cases_AIAN,Cases_NHPI,Cases_Multiracial,...,Tests_Latinx,Tests_Asian,Tests_AIAN,Tests_NHPI,Tests_Multiracial,Tests_Other,Tests_Unknown,Tests_Ethnicity_Hispanic,Tests_Ethnicity_NonHispanic,Tests_Ethnicity_Unknown
0,20210307,AK,59332.0,18300.0,1499.0,0.0,2447.0,12238.0,1508.0,4453.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,20210307,AL,499819.0,160347.0,82790.0,0.0,2273.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,20210307,AR,324818.0,207596.0,50842.0,0.0,2913.0,1070.0,3358.0,1804.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,20210307,AS,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,20210307,AZ,826454.0,308453.0,25775.0,244539.0,11921.0,40707.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5315,20200412,VT,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5316,20200412,WA,10411.0,2903.0,289.0,1180.0,451.0,41.0,61.0,112.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5317,20200412,WI,3341.0,1680.0,857.0,0.0,81.0,28.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5318,20200412,WV,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5319,20200412,WY,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [10]:
# Drop the null columns where all values are null
covidanalysis_data_df = covidanalysis_data_df.dropna(axis='columns', how='all')

In [11]:
covidanalysis_data_df

,Date,state,Cases_Total,Cases_White,Cases_Black,Cases_Latinx,Cases_Asian,Cases_AIAN,Cases_NHPI,Cases_Multiracial,...,Tests_Latinx,Tests_Asian,Tests_AIAN,Tests_NHPI,Tests_Multiracial,Tests_Other,Tests_Unknown,Tests_Ethnicity_Hispanic,Tests_Ethnicity_NonHispanic,Tests_Ethnicity_Unknown
0,20210307,AK,59332.0,18300.0,1499.0,NaN,2447.0,12238.0,1508.0,4453.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20210307,AL,499819.0,160347.0,82790.0,NaN,2273.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20210307,AR,324818.0,207596.0,50842.0,NaN,2913.0,1070.0,3358.0,1804.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20210307,AS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20210307,AZ,826454.0,308453.0,25775.0,244539.0,11921.0,40707.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5315,20200412,VT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5316,20200412,WA,10411.0,2903.0,289.0,1180.0,451.0,41.0,61.0,112.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5317,20200412,WI,3341.0,1680.0,857.0,NaN,81.0,28.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5318,20200412,WV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5319,20200412,WY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
# DESCRIPTIVE ANALYSIS
print(covidanalysis_df.describe())

               Date   Cases_Total    Cases_White    Cases_Black  Cases_Latinx  \
count  5.320000e+03  5.320000e+03    5320.000000    5320.000000  5.320000e+03
mean   2.020270e+07  1.829387e+05   61800.606015   17034.906579  2.383453e+04
std    3.745686e+03  3.406031e+05  101530.643105   30297.453274  9.943187e+04
min    2.020041e+07  0.000000e+00       0.000000       0.000000  0.000000e+00
25%    2.020070e+07  1.104550e+04    2857.000000     394.500000  0.000000e+00
50%    2.020092e+07  6.010100e+04   19007.000000    3909.500000  0.000000e+00
75%    2.020122e+07  2.016740e+05   69536.750000   19456.250000  1.029025e+04
max    2.021031e+07  3.501394e+06  664121.000000  237772.000000  1.509103e+06

         Cases_Asian    Cases_AIAN    Cases_NHPI  Cases_Multiracial  \
count    5320.000000   5320.000000   5320.000000        5320.000000
mean     3359.448872   1450.656579    382.711090         934.644925
std     11021.342617   4398.341645   1302.238605        3505.718519
min         0.000000      0.000000      0.000000           0.000000
25%        84.000000      0.000000      0.000000           0.000000
50%       825.000000     78.000000      0.000000           0.000000
75%      2929.500000    851.250000    132.250000          80.000000
max    186562.000000  41839.000000  15281.000000       42824.000000

         Cases_Other  ...  Tests_Latinx   Tests_Asian    Tests_AIAN  \
count    5320.000000  ...  5.320000e+03  5.320000e+03   5320.000000
mean     9688.536278  ...  2.985494e+04  1.207417e+04    613.109023
std     23883.038160  ...  4.238383e+05  1.573960e+05   4497.648156
min         0.000000  ...  0.000000e+00  0.000000e+00      0.000000
25%       154.000000  ...  0.000000e+00  0.000000e+00      0.000000
50%      1818.000000  ...  0.000000e+00  0.000000e+00      0.000000
75%      8620.000000  ...  0.000000e+00  0.000000e+00      0.000000
max    307324.000000  ...  1.072179e+07  3.980518e+06  98894.000000

          Tests_NHPI  Tests_Multiracial   Tests_Other  Tests_Unknown  \
count    5320.000000        5320.000000  5.320000e+03   5.320000e+03
mean      713.086842         149.254135  2.305907e+04   1.048104e+05
std      8958.049373        3451.708478  2.588845e+05   8.949176e+05
min         0.000000           0.000000  0.000000e+00   0.000000e+00
25%         0.000000           0.000000  0.000000e+00   0.000000e+00
50%         0.000000           0.000000  0.000000e+00   0.000000e+00
75%         0.000000           0.000000  0.000000e+00   0.000000e+00
max    222513.000000       98101.000000  6.354689e+06   1.856761e+07

       Tests_Ethnicity_Hispanic  Tests_Ethnicity_NonHispanic  \
count              5.320000e+03                 5.320000e+03
mean               3.162225e+04                 1.338365e+05
std                4.238686e+05                 1.006662e+06
min                0.000000e+00                 0.000000e+00
25%                0.000000e+00                 0.000000e+00
50%                0.000000e+00                 0.000000e+00
75%                0.000000e+00                 0.000000e+00
max                1.072179e+07                 2.163394e+07

       Tests_Ethnicity_Unknown
count             5.320000e+03
mean              1.179144e+05
std               9.049009e+05
min               0.000000e+00
25%               0.000000e+00
50%               0.000000e+00
75%               0.000000e+00
max               1.856761e+07

[8 rows x 53 columns]

In [13]:
covidanalysis_data_df = covidanalysis_data_df.dropna(axis='columns', how='all')

In [14]:
covidanalysis_data_df

,Date,state,Cases_Total,Cases_White,Cases_Black,Cases_Latinx,Cases_Asian,Cases_AIAN,Cases_NHPI,Cases_Multiracial,...,Tests_Latinx,Tests_Asian,Tests_AIAN,Tests_NHPI,Tests_Multiracial,Tests_Other,Tests_Unknown,Tests_Ethnicity_Hispanic,Tests_Ethnicity_NonHispanic,Tests_Ethnicity_Unknown
0,20210307,AK,59332.0,18300.0,1499.0,NaN,2447.0,12238.0,1508.0,4453.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20210307,AL,499819.0,160347.0,82790.0,NaN,2273.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20210307,AR,324818.0,207596.0,50842.0,NaN,2913.0,1070.0,3358.0,1804.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20210307,AS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20210307,AZ,826454.0,308453.0,25775.0,244539.0,11921.0,40707.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5315,20200412,VT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5316,20200412,WA,10411.0,2903.0,289.0,1180.0,451.0,41.0,61.0,112.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5317,20200412,WI,3341.0,1680.0,857.0,NaN,81.0,28.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5318,20200412,WV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5319,20200412,WY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
covidanalysis_encoded = pd.get_dummies(covidanalysis_df, columns=["state"])
covidanalysis_encoded

,Date,Cases_Total,Cases_White,Cases_Black,Cases_Latinx,Cases_Asian,Cases_AIAN,Cases_NHPI,Cases_Multiracial,Cases_Other,...,state_TN,state_TX,state_UT,state_VA,state_VI,state_VT,state_WA,state_WI,state_WV,state_WY
0,20210307,59332.0,18300.0,1499.0,0.0,2447.0,12238.0,1508.0,4453.0,7130.0,...,0,0,0,0,0,0,0,0,0,0
1,20210307,499819.0,160347.0,82790.0,0.0,2273.0,0.0,0.0,0.0,38000.0,...,0,0,0,0,0,0,0,0,0,0
2,20210307,324818.0,207596.0,50842.0,0.0,2913.0,1070.0,3358.0,1804.0,16491.0,...,0,0,0,0,0,0,0,0,0,0
3,20210307,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
4,20210307,826454.0,308453.0,25775.0,244539.0,11921.0,40707.0,0.0,0.0,46964.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5315,20200412,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,1,0,0,0,0
5316,20200412,10411.0,2903.0,289.0,1180.0,451.0,41.0,61.0,112.0,104.0,...,0,0,0,0,0,0,1,0,0,0
5317,20200412,3341.0,1680.0,857.0,0.0,81.0,28.0,0.0,0.0,74.0,...,0,0,0,0,0,0,0,1,0,0
5318,20200412,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,1,0
5319,20200412,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,1

In [16]:
covidanalysis_encoded.dtypes

Date              int64
Cases_Total     float64
Cases_White     float64
Cases_Black     float64
Cases_Latinx    float64
                 ...
state_VT          uint8
state_WA          uint8
state_WI          uint8
state_WV          uint8
state_WY          uint8
Length: 109, dtype: object

In [17]:
y = covidanalysis_encoded['Date']
X = pd.get_dummies(covidanalysis_encoded).drop('Date', axis=1) 
X.head()

,Cases_Total,Cases_White,Cases_Black,Cases_Latinx,Cases_Asian,Cases_AIAN,Cases_NHPI,Cases_Multiracial,Cases_Other,Cases_Unknown,...,state_TN,state_TX,state_UT,state_VA,state_VI,state_VT,state_WA,state_WI,state_WV,state_WY
0,59332.0,18300.0,1499.0,0.0,2447.0,12238.0,1508.0,4453.0,7130.0,11757.0,...,0,0,0,0,0,0,0,0,0,0
1,499819.0,160347.0,82790.0,0.0,2273.0,0.0,0.0,0.0,38000.0,216409.0,...,0,0,0,0,0,0,0,0,0,0
2,324818.0,207596.0,50842.0,0.0,2913.0,1070.0,3358.0,1804.0,16491.0,40744.0,...,0,0,0,0,0,0,0,0,0,0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
4,826454.0,308453.0,25775.0,244539.0,11921.0,40707.0,0.0,0.0,46964.0,148095.0,...,0,0,0,0,0,0,0,0,0,0

In [18]:
####linear regression
import numpy as np
from sklearn.linear_model import LinearRegression

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [20]:
# Create an instance of a linear regression model and fit it to the data with the fit() function:
model = LinearRegression().fit(X_train, y_train)

In [21]:
# Obtain the coefficient of determination by calling the model with the score() function, then print the coefficient:
r_sq = model.score(X_test, y_test)
print('coefficient of determination:', r_sq)

coefficient of determination: 0.5703788862651746

In [23]:
# Plot outputs
#y_pred = model.predict(X_test)
#plt.scatter(X_test, y_test, color="black")
#plt.plot(X_test, y_test, color="blue", linewidth=3)



#plt.show()

In [24]:

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import statsmodels.api as sm

In [25]:
covidanalysis_to_load = "./Race_and_Ethnicity.csv"
covidanalysis_data_df = pd.read_csv(covidanalysis_to_load)

In [26]:
y = covidanalysis_encoded['Date']
X = pd.get_dummies(covidanalysis_encoded).drop('Date', axis=1)

In [27]:
model = sm.OLS(y, X)
results = model.fit()
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                   Date   R-squared:                       0.607
Model:                            OLS   Adj. R-squared:                  0.599
Method:                 Least Squares   F-statistic:                     75.33
Date:                Thu, 31 Mar 2022   Prob (F-statistic):               0.00
Time:                        17:12:13   Log-Likelihood:                -48837.
No. Observations:                5320   AIC:                         9.789e+04
Df Residuals:                    5212   BIC:                         9.860e+04
Df Model:                         107
Covariance Type:            nonrobust
================================================================================================
                                   coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------
Cases_Total                      0.1172      0.012      9.604      0.000       0.093       0.141
Cases_White                     -0.0760      0.012     -6.091      0.000      -0.100      -0.052
Cases_Black                     -0.0307      0.009     -3.520      0.000      -0.048      -0.014
Cases_Latinx                     0.0137      0.016      0.874      0.382      -0.017       0.044
Cases_Asian                     -0.2212      0.028     -8.014      0.000      -0.275      -0.167
Cases_AIAN                       0.1496      0.026      5.841      0.000       0.099       0.200
Cases_NHPI                       0.4814      0.143      3.373      0.001       0.202       0.761
Cases_Multiracial               -0.1381      0.041     -3.396      0.001      -0.218      -0.058
Cases_Other                     -0.0644      0.016     -3.946      0.000      -0.096      -0.032
Cases_Unknown                   -0.0866      0.011     -7.589      0.000      -0.109      -0.064
Cases_Ethnicity_Hispanic        -0.1431      0.010    -14.113      0.000      -0.163      -0.123
Cases_Ethnicity_NonHispanic     -0.0222      0.004     -6.141      0.000      -0.029      -0.015
Cases_Ethnicity_Unknown         -0.0237      0.003     -7.536      0.000      -0.030      -0.018
Deaths_Total                    -1.7602      1.436     -1.226      0.220      -4.576       1.055
Deaths_White                     2.5691      1.449      1.773      0.076      -0.271       5.410
Deaths_Black                    -0.4847      1.467     -0.330      0.741      -3.362       2.392
Deaths_Latinx                    2.2096      1.553      1.423      0.155      -0.835       5.254
Deaths_Asian                     1.1162      1.820      0.613      0.540      -2.451       4.683
Deaths_AIAN                      0.9005      2.220      0.406      0.685      -3.451       5.252
Deaths_NHPI                     41.4487      9.202      4.504      0.000      23.409      59.488
Deaths_Multiracial              22.0641      3.413      6.465      0.000      15.374      28.755
Deaths_Other                     1.1938      1.512      0.789      0.430      -1.771       4.158
Deaths_Unknown                   1.8792      1.433      1.312      0.190      -0.929       4.688
Deaths_Ethnicity_Hispanic       -0.8809      0.511     -1.722      0.085      -1.884       0.122
Deaths_Ethnicity_NonHispanic    -0.1729      0.154     -1.122      0.262      -0.475       0.129
Deaths_Ethnicity_Unknown         0.7290      0.212      3.444      0.001       0.314       1.144
Hosp_Total                       0.5956      0.332      1.795      0.073      -0.055       1.246
Hosp_White                       0.5552      0.396      1.400      0.161      -0.222       1.332
Hosp_Black                       0.0233      0.358      0.065      0.948      -0.679       0.725
Hosp_Latinx                     -2.0413      0.566     -3.605      0.000      -3.151      -0.931
Hosp_Asian                       6.1733      0.769      8.032      0.000       4.667       7.680
Hosp_AIAN                        1.3992      0.504      2.779      0.005       0.412       2.386
Hosp_NHPI                       -3.6608      1.329     -2.754      0.006      -6.267      -1.055
Hosp_Multiracial               -12.8037      0.855    -14.969      0.000     -14.480     -11.127
Hosp_Other                       1.7433      0.514      3.391      0.001       0.735       2.751
Hosp_Unknown                    -0.0606      0.100     -0.609      0.543      -0.256       0.135
Hosp_Ethnicity_Hispanic          0.5606      0.441      1.271      0.204      -0.304       1.426
Hosp_Ethnicity_NonHispanic      -1.0760      0.189     -5.688      0.000      -1.447      -0.705
Hosp_Ethnicity_Unknown          -0.2227      0.323     -0.690      0.491      -0.856       0.410
Tests_Total                   -4.94e-05      0.000     -0.102      0.919      -0.001       0.001
Tests_White                      0.0005      0.006      0.090      0.928      -0.011       0.012
Tests_Black                      0.0275      0.010      2.751      0.006       0.008       0.047
Tests_Latinx                     0.0160      0.015      1.052      0.293      -0.014       0.046
Tests_Asian                      0.0155      0.009      1.784      0.075      -0.002       0.033
Tests_AIAN                       0.6715      0.106      6.330      0.000       0.464       0.879
Tests_NHPI                      -0.3934      0.073     -5.412      0.000      -0.536      -0.251
Tests_Multiracial                0.3949      0.077      5.118      0.000       0.244       0.546
Tests_Other                      0.0050      0.006      0.845      0.398      -0.007       0.017
Tests_Unknown                    0.0027      0.006      0.436      0.663      -0.009       0.015
Tests_Ethnicity_Hispanic        -0.0188      0.015     -1.232      0.218      -0.049       0.011
Tests_Ethnicity_NonHispanic     -0.0023      0.005     -0.458      0.647      -0.012       0.008
Tests_Ethnicity_Unknown         -0.0071      0.006     -1.185      0.236      -0.019       0.005
state_AK                       2.02e+07    261.168   7.73e+04      0.000    2.02e+07    2.02e+07
state_AL                       2.02e+07    278.497   7.25e+04      0.000    2.02e+07    2.02e+07
state_AR                       2.02e+07    340.111   5.94e+04      0.000    2.02e+07    2.02e+07
state_AS                       2.02e+07    243.287    8.3e+04      0.000    2.02e+07    2.02e+07
state_AZ                       2.02e+07    435.262   4.64e+04      0.000    2.02e+07    2.02e+07
state_CA                       2.02e+07    620.170   3.26e+04      0.000    2.02e+07    2.02e+07
state_CO                       2.02e+07    282.094   7.16e+04      0.000    2.02e+07    2.02e+07
state_CT                       2.02e+07    346.546   5.83e+04      0.000    2.02e+07    2.02e+07
state_DC                       2.02e+07    263.505   7.67e+04      0.000    2.02e+07    2.02e+07
state_DE                       2.02e+07    315.801    6.4e+04      0.000    2.02e+07    2.02e+07
state_FL                       2.02e+07    452.199   4.47e+04      0.000    2.02e+07    2.02e+07
state_GA                       2.02e+07    412.756   4.89e+04      0.000    2.02e+07    2.02e+07
state_GU                       2.02e+07    300.763   6.72e+04      0.000    2.02e+07    2.02e+07
state_HI                       2.02e+07    319.453   6.32e+04      0.000    2.02e+07    2.02e+07
state_IA                       2.02e+07    269.856   7.49e+04      0.000    2.02e+07    2.02e+07
state_ID                       2.02e+07    250.593   8.06e+04      0.000    2.02e+07    2.02e+07
state_IL                       2.02e+07    652.963   3.09e+04      0.000    2.02e+07    2.02e+07
state_IN                       2.02e+07    451.202   4.48e+04      0.000    2.02e+07    2.02e+07
state_KS                       2.02e+07    440.045   4.59e+04      0.000    2.02e+07    2.02e+07
state_KY                       2.02e+07    276.046   7.32e+04      0.000    2.02e+07    2.02e+07
state_LA                       2.02e+07    525.054   3.85e+04      0.000    2.02e+07    2.02e+07
state_MA                       2.02e+07    500.397   4.04e+04      0.000    2.02e+07    2.02e+07
state_MD                       2.02e+07    331.242    6.1e+04      0.000    2.02e+07    2.02e+07
state_ME                       2.02e+07    244.437   8.26e+04      0.000    2.02e+07    2.02e+07
state_MI                       2.02e+07    643.233   3.14e+04      0.000    2.02e+07    2.02e+07
state_MN                       2.02e+07    339.937   5.94e+04      0.000    2.02e+07    2.02e+07
state_MO                       2.02e+07    288.123   7.01e+04      0.000    2.02e+07    2.02e+07
state_MP                       2.02e+07    243.287    8.3e+04      0.000    2.02e+07    2.02e+07
state_MS                       2.02e+07    318.325   6.35e+04      0.000    2.02e+07    2.02e+07
state_MT                       2.02e+07    313.900   6.44e+04      0.000    2.02e+07    2.02e+07
state_NC                       2.02e+07    398.824   5.07e+04      0.000    2.02e+07    2.02e+07
state_ND                       2.02e+07    260.346   7.76e+04      0.000    2.02e+07    2.02e+07
state_NE                       2.02e+07    327.305   6.17e+04      0.000    2.02e+07    2.02e+07
state_NH                       2.02e+07    245.067   8.24e+04      0.000    2.02e+07    2.02e+07
state_NJ                       2.02e+07    578.579   3.49e+04      0.000    2.02e+07    2.02e+07
state_NM                       2.02e+07    385.620   5.24e+04      0.000    2.02e+07    2.02e+07
state_NV                       2.02e+07    334.595   6.04e+04      0.000    2.02e+07    2.02e+07
state_NY                       2.02e+07   1244.237   1.62e+04      0.000    2.02e+07    2.02e+07
state_OH                       2.02e+07    409.523   4.93e+04      0.000    2.02e+07    2.02e+07
state_OK                       2.02e+07    321.834   6.28e+04      0.000    2.02e+07    2.02e+07
state_OR                       2.02e+07    325.962    6.2e+04      0.000    2.02e+07    2.02e+07
state_PA                       2.02e+07    462.719   4.37e+04      0.000    2.02e+07    2.02e+07
state_PR                       2.02e+07    294.800   6.85e+04      0.000    2.02e+07    2.02e+07
state_RI                       2.02e+07    298.658   6.76e+04      0.000    2.02e+07    2.02e+07
state_SC                       2.02e+07    286.712   7.05e+04      0.000    2.02e+07    2.02e+07
state_SD                       2.02e+07    269.894   7.48e+04      0.000    2.02e+07    2.02e+07
state_TN                       2.02e+07    296.011   6.82e+04      0.000    2.02e+07    2.02e+07
state_TX                       2.02e+07    410.535   4.92e+04      0.000    2.02e+07    2.02e+07
state_UT                       2.02e+07    381.746   5.29e+04      0.000    2.02e+07    2.02e+07
state_VA                       2.02e+07    302.653   6.67e+04      0.000    2.02e+07    2.02e+07
state_VI                       2.02e+07    243.293    8.3e+04      0.000    2.02e+07    2.02e+07
state_VT                       2.02e+07    243.364    8.3e+04      0.000    2.02e+07    2.02e+07
state_WA                       2.02e+07    321.761   6.28e+04      0.000    2.02e+07    2.02e+07
state_WI                       2.02e+07    301.120   6.71e+04      0.000    2.02e+07    2.02e+07
state_WV                       2.02e+07    270.052   7.48e+04      0.000    2.02e+07    2.02e+07
state_WY                       2.02e+07    245.898   8.22e+04      0.000    2.02e+07    2.02e+07
==============================================================================
Omnibus:                      789.931   Durbin-Watson:                   0.789
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1444.922
Skew:                           0.947   Prob(JB):                         0.00
Kurtosis:                       4.712   Cond. No.                     1.24e+08
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.24e+08. This might indicate that there are
strong multicollinearity or other numerical problems.

In [ ]:
# Resample the training data with the BalancedRandomForestClassifier
#from sklearn.metrics import balanced_accuracy_score
#from sklearn.model_selection import train_test_split

In [ ]:
#from sklearn.model_selection import train_test_split
#X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [ ]:

#from imblearn.ensemble import BalancedRandomForestClassifier
# Instantiate
#brfc = BalancedRandomForestClassifier(n_estimators=500, random_state=1)

# Fit
#brfc.fit(X_train, y_train)

In [ ]:
# Calculated the balanced accuracy score
#y_pred = brfc.predict(X_test)
#balanced_accuracy_score(y_test, y_test)

In [ ]:
# Train the EasyEnsembleClassifier
#from sklearn.metrics import balanced_accuracy_score
#from sklearn.model_selection import train_test_split

In [ ]:
#from imblearn.ensemble import EasyEnsembleClassifier
# Instantiate
#eec = EasyEnsembleClassifier(n_estimators=500, random_state=1)

# Fit
#eec.fit(X_train, y_train)

In [ ]:
# Calculated the balanced accuracy score
#y_pred = eec.predict(X_test)
#balanced_accuracy_score(y_test, y_test)

In [28]:
import tensorflow as tf
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [29]:
#y = covidanalysis_encoded['Women']
#X = pd.get_dummies(covidanalysis_encoded).drop('Women', axis=1) 
#X.head()

In [30]:
# Define the basic neural network model
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [31]:
# Create scaler instance
X_scaler = skl.preprocessing.StandardScaler()

# Fit the scaler
X_scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [32]:
# Create the Keras Sequential model
nn_model = tf.keras.models.Sequential()

2022-03-31 17:12:24.191946: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [33]:
# Define the basic neural network model

nn_model.add(tf.keras.layers.Dense(units=16, activation="relu", input_dim=2))
nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))
# Check the structure of the Sequential model
nn_model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 16)                48
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 17
=================================================================
Total params: 65
Trainable params: 65
Non-trainable params: 0
_________________________________________________________________

In [34]:
# Compile the Sequential model together and customize metrics
nn_model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [35]:
# Train the model
fit_model = nn_model.fit(X_train_scaled, y_train, epochs=100)

2022-03-31 17:12:26.552143: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)

Epoch 1/100

ValueError: in user code:

    /Users/944allview/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/keras/engine/training.py:853 train_function  *
        return step_function(self, iterator)
    /Users/944allview/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/keras/engine/training.py:842 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    /Users/944allview/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:1286 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /Users/944allview/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:2849 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /Users/944allview/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:3632 _call_for_each_replica
        return fn(*args, **kwargs)
    /Users/944allview/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/keras/engine/training.py:835 run_step  **
        outputs = model.train_step(data)
    /Users/944allview/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/keras/engine/training.py:787 train_step
        y_pred = self(x, training=True)
    /Users/944allview/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/keras/engine/base_layer.py:1020 __call__
        input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)
    /Users/944allview/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/keras/engine/input_spec.py:254 assert_input_compatibility
        ' but received input with shape ' + display_shape(x.shape))

    ValueError: Input 0 of layer sequential is incompatible with the layer: expected axis -1 of input shape to have value 2 but received input with shape (None, 108)

In [36]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

ValueError: in user code:

    /Users/944allview/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/keras/engine/training.py:1330 test_function  *
        return step_function(self, iterator)
    /Users/944allview/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/keras/engine/training.py:1320 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    /Users/944allview/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:1286 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /Users/944allview/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:2849 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /Users/944allview/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:3632 _call_for_each_replica
        return fn(*args, **kwargs)
    /Users/944allview/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/keras/engine/training.py:1313 run_step  **
        outputs = model.test_step(data)
    /Users/944allview/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/keras/engine/training.py:1267 test_step
        y_pred = self(x, training=False)
    /Users/944allview/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/keras/engine/base_layer.py:1020 __call__
        input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)
    /Users/944allview/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/keras/engine/input_spec.py:254 assert_input_compatibility
        ' but received input with shape ' + display_shape(x.shape))

    ValueError: Input 0 of layer sequential is incompatible with the layer: expected axis -1 of input shape to have value 2 but received input with shape (None, 108)

In [ ]:
import tensorflow as tf
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [ ]:
# Preprocess numerical data for neural network

# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [ ]:
# Define the logistic regression model
log_classifier = LogisticRegression(solver="lbfgs",max_iter=1000)

# Train the model
log_classifier.fit(X,y)

# Evaluate the model
y_pred = log_classifier.predict(X)
print(f" Logistic regression model accuracy: {accuracy_score(y,y_pred):.3f}")

In [ ]:
### SVM support vector machine

In [41]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC
import pandas as pd
import tensorflow as tf

# Import our input dataset
covidanalysis_data_df = pd.read_csv(covidanalysis_to_load)
covidanalysis_data_df

,Date,state,Cases_Total,Cases_White,Cases_Black,Cases_Latinx,Cases_Asian,Cases_AIAN,Cases_NHPI,Cases_Multiracial,...,Tests_Latinx,Tests_Asian,Tests_AIAN,Tests_NHPI,Tests_Multiracial,Tests_Other,Tests_Unknown,Tests_Ethnicity_Hispanic,Tests_Ethnicity_NonHispanic,Tests_Ethnicity_Unknown
0,20210307,AK,59332.0,18300.0,1499.0,NaN,2447.0,12238.0,1508.0,4453.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20210307,AL,499819.0,160347.0,82790.0,NaN,2273.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20210307,AR,324818.0,207596.0,50842.0,NaN,2913.0,1070.0,3358.0,1804.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20210307,AS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20210307,AZ,826454.0,308453.0,25775.0,244539.0,11921.0,40707.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5315,20200412,VT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5316,20200412,WA,10411.0,2903.0,289.0,1180.0,451.0,41.0,61.0,112.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5317,20200412,WI,3341.0,1680.0,857.0,NaN,81.0,28.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5318,20200412,WV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5319,20200412,WY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [42]:
# Generate our categorical variable list
covid_cat = covidanalysis_data_df.dtypes[covidanalysis_data_df.dtypes == "object"].index.tolist()


# Check the number of unique values in each column
covidanalysis_data_df[covid_cat].nunique()

state    56
dtype: int64

In [43]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

# Fit and transform the OneHotEncoder using the categorical variable list
covid_df = pd.DataFrame(enc.fit_transform(covidanalysis_data_df[covid_cat]))

# Add the encoded variable names to the dataframe
covid_df.columns = enc.get_feature_names(covid_cat)
covid_df.head()

/Users/944allview/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,state_AK,state_AL,state_AR,state_AS,state_AZ,state_CA,state_CO,state_CT,state_DC,state_DE,...,state_TN,state_TX,state_UT,state_VA,state_VI,state_VT,state_WA,state_WI,state_WV,state_WY
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [44]:
# Merge one-hot encoded features and drop the originals
covid_df = covidanalysis_data_df.merge(covid_df,left_index=True, right_index=True)
covid_df = covidanalysis_data_df.drop(covid_cat,1)
covid_df.head()

/Users/944allview/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/ipykernel_launcher.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  This is separate from the ipykernel package so we can avoid doing imports until

,Date,Cases_Total,Cases_White,Cases_Black,Cases_Latinx,Cases_Asian,Cases_AIAN,Cases_NHPI,Cases_Multiracial,Cases_Other,...,Tests_Latinx,Tests_Asian,Tests_AIAN,Tests_NHPI,Tests_Multiracial,Tests_Other,Tests_Unknown,Tests_Ethnicity_Hispanic,Tests_Ethnicity_NonHispanic,Tests_Ethnicity_Unknown
0,20210307,59332.0,18300.0,1499.0,NaN,2447.0,12238.0,1508.0,4453.0,7130.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20210307,499819.0,160347.0,82790.0,NaN,2273.0,NaN,NaN,NaN,38000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20210307,324818.0,207596.0,50842.0,NaN,2913.0,1070.0,3358.0,1804.0,16491.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20210307,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20210307,826454.0,308453.0,25775.0,244539.0,11921.0,40707.0,NaN,NaN,46964.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [45]:
# Split training/test datasets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [46]:
# Create a StandardScaler instance
scaler = StandardScaler()

In [47]:
# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

In [48]:
# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [49]:
# Create the SVM model
from sklearn.svm import SVC
svm = SVC(kernel='linear')

In [ ]:
# Train the model
svm.fit(X_train, y_train)

In [ ]:
y_pred = model.predict(X_test)
results = pd.DataFrame({
   "Prediction": y_pred,
   "Actual": y_test
}).reset_index(drop=True)
results.head()

In [ ]:
# Evaluate the model
y_pred = svm.predict(X_test)
print(f" SVM model accuracy: {accuracy_score(y_test,y_pred):.3f}")

In [ ]:
#from sklearn.metrics import confusion_matrix
#confusion_matrix(y_test, y_pred)

#from sklearn.metrics import classification_report
#print(classification_report(y_test, y_pred))

In [ ]:
# Define the model - deep neural net
#number_input_features = len(X_train_scaled[0])
#hidden_nodes_layer1 = 10
#hidden_nodes_layer2 = 5

#nn = tf.keras.models.Sequential()

# First hidden layer
#nn.add(
   # tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
#)

# Second hidden layer
#nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))


# Output layer
#nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Compile the Sequential model together and customize metrics
#nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [ ]:
# Train the model 
#fit_model = nn.fit(X_train_scaled, y_train, epochs=50) 
# Evaluate the model using the test data 
#model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
#print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")